### ISSUE TITLE
Which facebook cookie needs to be used?

### ISSUE THREAD

**Issue by rofrol** [karlicoss/fbmessengerexport#7]

**Comment by karlicoss** [comment]
Hi, when you run `--login` (as per instructions https://github.com/karlicoss/fbmessengerexport#setting-up), it dumps the string you need to set as `cookies` variable. Doesn't this work for you?

**Comment by jcguu95** [comment]
The doc used to be a bit confusing, fixed [here](https://github.com/karlicoss/fbmessengerexport/pull/11).. closing?

**Comment by rofrol** [comment]
Thanks
