### ISSUE TITLE
Not giving any results

### ISSUE THREAD

**Issue by oliviernguyenquoc** [karlicoss/fbmessengerexport#9]
Hi,

It's running for 2h30 and it seems that the DB is still empty:
`sqlite3 mydb.db`
`.table` => Return empty

Moreover, I have a lot of lines like:
```shell
[W 201230 14:32:38 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:32:38 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:32:48 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:32:48 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:32:58 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:32:58 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:33:08 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:33:08 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:33:17 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
[W 201230 14:33:18 export:356] Filtered out 1 threads of type MARKETPLACE. See https://github.com/carpedm20/fbchat/issues/408
```

Something is not running well ?
Did I make something wrong ?

**Comment by karlicoss** [comment]
Hmm, this is weird. The logs seem related to this https://github.com/karlicoss/fbmessengerexport/issues/2 ; basically facebook marketplace message are unsupported by the `fbchat` library, so this hack skips them. So the warning is just merely a warning, apart from it it should work. But it's weird that there are no messages in the database.

Maybe a good start would be to put a breakpoint or some logging at line 205 https://github.com/karlicoss/fbmessengerexport/blob/92d3a250f45b389f5249e615667bd755ee6f90a9/src/fbmessengerexport/export.py#L203-L207? At this point you could at least inspect `threads` variable and the threads should be in the database as well.

**Comment by oliviernguyenquoc** [comment]
Thanks for your answer. Just retry today. It works. 
Weird stuff from Facebook side I guess...

Thanks for sharing your work in open source. ;)
